[agmsg]
fetch.github = "fujibee/agmsg"
src.manual = "v1.1.8"

[deck]
fetch.github = "k1LoW/deck"
src.manual = "v1.24.0"

[diffyml]
fetch.github = "szhekpisov/diffyml"
src.manual = "v1.7.1"

[difit]
fetch.github = "yoshiko-pg/difit"
src.manual = "v5.0.6"

[github-comment]
fetch.github = "suzuki-shunsuke/github-comment"
src.manual = "v6.3.2"

[leaf]
fetch.github = "RivoLink/leaf"
src.manual = "1.26.0"

[tfcmt]
fetch.github = "suzuki-shunsuke/tfcmt"
src.manual = "v4.14.7"

[vde-layout]
fetch.github = "yuki-yano/vde-layout"
src.manual = "v1.1.1"

[yashiki]
fetch.github = "typester/yashiki"
src.manual = "yashiki-v0.15.2"
