# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  agmsg = {
    pname = "agmsg";
    version = "v1.1.8";
    src = fetchFromGitHub {
      owner = "fujibee";
      repo = "agmsg";
      rev = "v1.1.8";
      fetchSubmodules = false;
      sha256 = "sha256-p2K4w1hHkldw4HWAO2EpSX0eLwUGH/ae0BAIadblvPA=";
    };
  };
  deck = {
    pname = "deck";
    version = "v1.24.1";
    src = fetchFromGitHub {
      owner = "k1LoW";
      repo = "deck";
      rev = "v1.24.1";
      fetchSubmodules = false;
      sha256 = "sha256-uLuVHgI0Mp6d3ZZoKK6I+Hcg3uQ0iYUle1E0exbf2h4=";
    };
  };
  diffyml = {
    pname = "diffyml";
    version = "v1.7.1";
    src = fetchFromGitHub {
      owner = "szhekpisov";
      repo = "diffyml";
      rev = "v1.7.1";
      fetchSubmodules = false;
      sha256 = "sha256-bfFerbjpwQuTCnGKfqUj3ydf1xBdNoP+qH7UTmtZvTk=";
    };
  };
  difit = {
    pname = "difit";
    version = "v5.0.7";
    src = fetchFromGitHub {
      owner = "yoshiko-pg";
      repo = "difit";
      rev = "v5.0.7";
      fetchSubmodules = false;
      sha256 = "sha256-LwqfnZTo4m+B2rpMWY0SEomsVtSuCxqnM24D9bq9j40=";
    };
  };
  github-comment = {
    pname = "github-comment";
    version = "v6.3.2";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "github-comment";
      rev = "v6.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-6aRgbxa5C6pgYgeTE/vRcqvW1iQjzPxJwQbZMmUo/90=";
    };
  };
  leaf = {
    pname = "leaf";
    version = "1.26.0";
    src = fetchFromGitHub {
      owner = "RivoLink";
      repo = "leaf";
      rev = "1.26.0";
      fetchSubmodules = false;
      sha256 = "sha256-/tMlInOT7ipqZ3ONE70QgmPUw9nDC5+7vgdpCyXqr2E=";
    };
  };
  tfcmt = {
    pname = "tfcmt";
    version = "v4.14.15";
    src = fetchFromGitHub {
      owner = "suzuki-shunsuke";
      repo = "tfcmt";
      rev = "v4.14.15";
      fetchSubmodules = false;
      sha256 = "sha256-+F+g8fDleZ0bP57aAjMytUfT2sNhf/4T5XlE4+cJwgA=";
    };
  };
  vde-layout = {
    pname = "vde-layout";
    version = "v1.1.1";
    src = fetchFromGitHub {
      owner = "yuki-yano";
      repo = "vde-layout";
      rev = "v1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-sqF/F3g2NoJdVEx98JeTLQGBtm2bD1h0tLQAjD+v+04=";
    };
  };
  yashiki = {
    pname = "yashiki";
    version = "yashiki-v0.15.2";
    src = fetchFromGitHub {
      owner = "typester";
      repo = "yashiki";
      rev = "yashiki-v0.15.2";
      fetchSubmodules = false;
      sha256 = "sha256-nsmUuhi0yy6x6POC4qLbMib4fxS3QRjlK6QgCiVEnyQ=";
    };
  };
}
